<a href="https://colab.research.google.com/github/kimtomato/torch_example/blob/main/Logistic_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch 
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)

In [2]:
x_data = [[1, 2], [2, 3], [3, 1], [4, 3], [5, 3], [6, 2]]
y_data = [[0], [0], [0], [1], [1], [1]]
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

In [3]:
     W = torch.zeros((2,1), requires_grad=True)
     b = torch.zeros(1, requires_grad=True)

In [6]:
h= 1/(1+torch.exp(-(x_train.matmul(W)+b)))

h= torch.sigmoid(x_train.matmul(W)+b)

print(h)
print(y_train)

tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000]], grad_fn=<SigmoidBackward0>)
tensor([[0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.]])


In [7]:
losses = -(y_train*torch.log(h) + (1-y_train)*torch.log(1-h))

print(losses)

tensor([[0.6931],
        [0.6931],
        [0.6931],
        [0.6931],
        [0.6931],
        [0.6931]], grad_fn=<NegBackward0>)


In [8]:
cost = losses.mean()

In [9]:
F.binary_cross_entropy(h, y_train)

tensor(0.6931, grad_fn=<BinaryCrossEntropyBackward0>)

In [12]:
W = torch.zeros((2, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)

optimizer = optim.SGD([W,b], lr=1)

nb_epoch=1000

for epoch in range(nb_epoch+1):

    h = torch.sigmoid(x_train.matmul(W)+b)
    cost = F.binary_cross_entropy(h, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
            epoch, nb_epoch, cost.item()
        ))

Epoch    0/1000 Cost: 0.693147
Epoch  100/1000 Cost: 0.134722
Epoch  200/1000 Cost: 0.080643
Epoch  300/1000 Cost: 0.057900
Epoch  400/1000 Cost: 0.045300
Epoch  500/1000 Cost: 0.037261
Epoch  600/1000 Cost: 0.031673
Epoch  700/1000 Cost: 0.027556
Epoch  800/1000 Cost: 0.024394
Epoch  900/1000 Cost: 0.021888
Epoch 1000/1000 Cost: 0.019852


In [14]:
h = torch.sigmoid(x_train.matmul(W) + b)
print(h)



prediction = h >= torch.FloatTensor([0.5])
print(prediction)

tensor([[2.7648e-04],
        [3.1608e-02],
        [3.8977e-02],
        [9.5622e-01],
        [9.9823e-01],
        [9.9969e-01]], grad_fn=<SigmoidBackward0>)
tensor([[False],
        [False],
        [False],
        [ True],
        [ True],
        [ True]])


In [16]:
  #nn.module로 구현 

  import torch 
  import torch.nn as nn 
  import torch.nn.functional as F

torch.manual_seed(1)

x_data = [[1, 2], [2, 3], [3, 1], [4, 3], [5, 3], [6, 2]]
y_data = [[0], [0], [0], [1], [1], [1]]
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

In [19]:
model = nn.Sequential(
    nn.Linear(2,1),
    nn.Sigmoid()
)

print(model(x_train))

tensor([[0.3600],
        [0.2872],
        [0.6801],
        [0.4389],
        [0.5216],
        [0.7473]], grad_fn=<SigmoidBackward0>)


In [20]:
optimizer = optim.SGD(model.parameters(), lr=1)

nb_epochs = 1000
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    hypothesis = model(x_train)

    # cost 계산
    cost = F.binary_cross_entropy(hypothesis, y_train)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 20번마다 로그 출력
    if epoch % 10 == 0:
        prediction = hypothesis >= torch.FloatTensor([0.5]) # 예측값이 0.5를 넘으면 True로 간주
        correct_prediction = prediction.float() == y_train # 실제값과 일치하는 경우만 True로 간주
        accuracy = correct_prediction.sum().item() / len(correct_prediction) # 정확도를 계산
        print('Epoch {:4d}/{} Cost: {:.6f} Accuracy {:2.2f}%'.format( # 각 에포크마다 정확도를 출력
            epoch, nb_epochs, cost.item(), accuracy * 100,
        ))

Epoch    0/1000 Cost: 0.614994 Accuracy 66.67%
Epoch   10/1000 Cost: 0.747550 Accuracy 83.33%
Epoch   20/1000 Cost: 0.633216 Accuracy 83.33%
Epoch   30/1000 Cost: 0.538123 Accuracy 83.33%
Epoch   40/1000 Cost: 0.450406 Accuracy 83.33%
Epoch   50/1000 Cost: 0.366382 Accuracy 83.33%
Epoch   60/1000 Cost: 0.287368 Accuracy 83.33%
Epoch   70/1000 Cost: 0.219288 Accuracy 83.33%
Epoch   80/1000 Cost: 0.173225 Accuracy 100.00%
Epoch   90/1000 Cost: 0.151674 Accuracy 100.00%
Epoch  100/1000 Cost: 0.140280 Accuracy 100.00%
Epoch  110/1000 Cost: 0.131002 Accuracy 100.00%
Epoch  120/1000 Cost: 0.122903 Accuracy 100.00%
Epoch  130/1000 Cost: 0.115765 Accuracy 100.00%
Epoch  140/1000 Cost: 0.109426 Accuracy 100.00%
Epoch  150/1000 Cost: 0.103760 Accuracy 100.00%
Epoch  160/1000 Cost: 0.098664 Accuracy 100.00%
Epoch  170/1000 Cost: 0.094056 Accuracy 100.00%
Epoch  180/1000 Cost: 0.089870 Accuracy 100.00%
Epoch  190/1000 Cost: 0.086050 Accuracy 100.00%
Epoch  200/1000 Cost: 0.082549 Accuracy 100.00%


In [40]:
## Class로 구현하기 

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
x_data = [[1, 2], [2, 3], [3, 1], [4, 3], [5, 3], [6, 2]]
y_data = [[0], [0], [0], [1], [1], [1]]
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)


class BinaryClassifier(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(2,1)
        self.sigmoid = nn.Sigmoid()


    def forward(self,x):
        return self.sigmoid(self.linear(x))



model = BinaryClassifier()

In [41]:
print(list(model.parameters()))

[Parameter containing:
tensor([[ 0.3843, -0.6912]], requires_grad=True), Parameter containing:
tensor([0.4383], requires_grad=True)]


In [42]:
optimizer = optim.SGD(model.parameters(), lr =1)

nb_epochs = 1000
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    hypothesis = model(x_train)

    # cost 계산
    cost = F.binary_cross_entropy(hypothesis, y_train)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 20번마다 로그 출력
    if epoch % 10 == 0:
        prediction = hypothesis >= torch.FloatTensor([0.5]) # 예측값이 0.5를 넘으면 True로 간주
        correct_prediction = prediction.float() == y_train # 실제값과 일치하는 경우만 True로 간주
        accuracy = correct_prediction.sum().item() / len(correct_prediction) # 정확도를 계산
        print('Epoch {:4d}/{} Cost: {:.6f} Accuracy {:2.2f}%'.format( # 각 에포크마다 정확도를 출력
            epoch, nb_epochs, cost.item(), accuracy * 100,
        ))

Epoch    0/1000 Cost: 0.595946 Accuracy 66.67%
Epoch   10/1000 Cost: 0.707535 Accuracy 83.33%
Epoch   20/1000 Cost: 0.638608 Accuracy 83.33%
Epoch   30/1000 Cost: 0.540139 Accuracy 83.33%
Epoch   40/1000 Cost: 0.452255 Accuracy 83.33%
Epoch   50/1000 Cost: 0.368146 Accuracy 83.33%
Epoch   60/1000 Cost: 0.288984 Accuracy 83.33%
Epoch   70/1000 Cost: 0.220561 Accuracy 83.33%
Epoch   80/1000 Cost: 0.173926 Accuracy 100.00%
Epoch   90/1000 Cost: 0.151975 Accuracy 100.00%
Epoch  100/1000 Cost: 0.140495 Accuracy 100.00%
Epoch  110/1000 Cost: 0.131188 Accuracy 100.00%
Epoch  120/1000 Cost: 0.123066 Accuracy 100.00%
Epoch  130/1000 Cost: 0.115910 Accuracy 100.00%
Epoch  140/1000 Cost: 0.109555 Accuracy 100.00%
Epoch  150/1000 Cost: 0.103875 Accuracy 100.00%
Epoch  160/1000 Cost: 0.098768 Accuracy 100.00%
Epoch  170/1000 Cost: 0.094151 Accuracy 100.00%
Epoch  180/1000 Cost: 0.089956 Accuracy 100.00%
Epoch  190/1000 Cost: 0.086128 Accuracy 100.00%
Epoch  200/1000 Cost: 0.082621 Accuracy 100.00%
